name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # Install protoc if needed
    - name: Install protoc Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install protobuf-compiler
    - name: Install protoc MacOS
      if: matrix.os == 'macos-latest'
      run: brew install protobuf
    - name: Install protoc Windows
      if: matrix.os == 'windows-latest'
      run: winget install --id Google.Protobuf --source winget

    - name: Build
      run: cargo build --bin server --release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: server-${{ matrix.os }}
        path: target/release/server
        compression-level: 9