name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      run: sudo apt-get install protobuf-compiler
    - name: Build
      run: cargo build --bin server --release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: server-linux
        path: target/release/server
        compression-level: 9
