name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      run: sudo apt-get install protobuf-compiler
    - name: Build
      run: cargo build --bin server --release --verbose
    - name: Zip
      run: zip -j server.zip target/release/server
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: server
